<script setup lang="ts">
import {withBase} from 'vitepress';
const links = (path: string) => withBase(path);
</script>
<template>
  <main class="master-home">
    <section class="master-hero"><div class="hero-grid" aria-hidden="true"/><div class="hero-copy"><p class="kicker">MASTERSEED · TYPESCRIPT + GO SDK · KEYMASTER SEED V1</p><h1>Make data<br><em>checkable.</em></h1><p class="summary">A deterministic seed of raw SHA-256 block digests for content verification across TypeScript and Go.</p><div class="actions"><a class="action primary" :href="links('/guide/getting-started')">Start integrating ↗</a><a class="action" :href="links('/api/typescript/')">Read the API</a></div><p class="install"><b>$</b> <span class="command">npm install masterseed</span> <span class="command">go get github.com/bsv8/MasterSeed</span></p></div><div class="data-field" role="img" aria-label="Source blocks become a digest stream and then a seed hash"><div class="orbit"><i>01</i><i>02</i><i>03</i><strong>BLOCKS → DIGESTS → HASH</strong></div></div></section>
    <section class="flow"><p class="index">01 / FORMAT FLOW</p><h2>Bytes in.<br><em>Evidence out.</em></h2><p class="flow-copy">Chunk boundaries are protocol boundaries, not iterable boundaries. Every SDK emits one raw digest per 256 KiB source block.</p><ol><li><span>01</span><strong>Source blocks</strong><small>Read up to 262144 bytes.</small></li><li><span>02</span><strong>Digest stream</strong><small>SHA-256, raw 32-byte values.</small></li><li><span>03</span><strong>Seed hash</strong><small>SHA256(seed_bytes).</small></li></ol></section>
    <section class="boundary"><p class="index">02 / LANGUAGE BOUNDARY</p><h2>One contract.<br><em>Two native edges.</em></h2><div class="rows"><a :href="links('/guide/typescript-core')"><span>TS</span><strong>Async iterable core</strong><small>ByteSource, sinks, and bigint sizes.</small><b>↗</b></a><a :href="links('/guide/go-streaming')"><span>GO</span><strong>Context + io.Reader / io.Writer</strong><small>Streaming operations in the root package.</small><b>↗</b></a><a :href="links('/api/typescript/')"><span>TS API</span><strong>Generated TypeDoc reference</strong><small>Built from ../typescript/src/index.ts.</small><b>↗</b></a><a :href="links('/api/go/')"><span>GO API</span><strong>Generated gomarkdoc reference</strong><small>Built from the root package comments.</small><b>↗</b></a></div></section>
    <section class="final"><p class="index">03 / START HERE</p><h2>Ship a verifiable<br><em>data boundary.</em></h2><a class="action primary" :href="links('/guide/getting-started')">Open the guide →</a></section>
  </main>
</template>
