import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars:SidebarsConfig={guide:[{type:'category',label:'Guide',items:['guide/getting-started','guide/create-verify','guide/block-operations','guide/errors']}],concepts:[{type:'category',label:'Concepts',items:['concepts/seed-v1','concepts/interoperability','concepts/security']}],api:[{type:'category',label:'TypeScript API',items:[{type:'autogenerated',dirName:'api/typescript'}]},{type:'category',label:'Go API',items:[{type:'autogenerated',dirName:'api/go'}]}]};
export default sidebars;
